In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
import pandas as pd

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler 
from sklearn.tree import DecisionTreeClassifier

In [9]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [11]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [12]:
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns='Survived'),df[['Survived']],test_size=0.2)

In [13]:
x_train

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
244       3    male  30.0      0      0   7.2250        C
296       3    male  23.5      0      0   7.2292        C
350       3    male  23.0      0      0   9.2250        S
504       1  female  16.0      0      0  86.5000        S
797       3  female  31.0      0      0   8.6833        S
..      ...     ...   ...    ...    ...      ...      ...
589       3    male   NaN      0      0   8.0500        S
59        3    male  11.0      5      2  46.9000        S
611       3    male   NaN      0      0   7.0500        S
841       2    male  16.0      0      0  10.5000        S
857       1    male  51.0      0      0  26.5500        S

[712 rows x 7 columns]

In [14]:
y_train

Survived
244         0
296         0
350         0
504         1
797         1
..        ...
589         0
59          0
611         0
841         0
857         1

[712 rows x 1 columns]

In [15]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [16]:
si = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [17]:
x_train_age = si.fit_transform(x_train[['Age']])

In [18]:
x_train_age

array([[30.        ],
       [23.5       ],
       [23.        ],
       [16.        ],
       [31.        ],
       [29.58908127],
       [29.        ],
       [23.        ],
       [35.        ],
       [39.        ],
       [16.        ],
       [18.        ],
       [34.        ],
       [29.        ],
       [50.        ],
       [32.        ],
       [49.        ],
       [29.        ],
       [42.        ],
       [18.        ],
       [ 2.        ],
       [18.        ],
       [17.        ],
       [29.58908127],
       [14.5       ],
       [29.58908127],
       [30.        ],
       [35.        ],
       [47.        ],
       [51.        ],
       [28.        ],
       [23.        ],
       [29.58908127],
       [21.        ],
       [18.        ],
       [39.        ],
       [16.        ],
       [25.        ],
       [ 1.        ],
       [29.        ],
       [26.        ],
       [11.        ],
       [25.        ],
       [30.        ],
       [32.        ],
       [18

In [19]:
x_train_embark = si_embarked.fit_transform(x_train[['Embarked']])

In [20]:
x_train_embark[2]

array(['S'], dtype=object)

In [21]:
x_test_age = si.transform(x_test[['Age']])
x_test_age.shape

(179, 1)

In [22]:
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

In [23]:
x_test_embarked[1]

array(['Q'], dtype=object)

In [24]:
ohe = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [25]:
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [26]:
x_train_gender = ohe.fit_transform(x_train[['Sex']])
x_train_embark = ohe_embarked.fit_transform(x_train_embark)

In [27]:
x_test_gender = ohe.transform(x_test[['Sex']])

In [28]:
x_train_gender

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], shape=(712, 2))

In [29]:
x_test_embarked = ohe_embarked.transform(x_test[['Embarked']])

d:\featureEngineering\featureEngineering\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


In [30]:
x_train_embark

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [31]:
x_train_rem = x_train.drop(columns=['Sex','Age','Embarked'])
x_test_rem = x_test.drop(columns=['Sex','Age','Embarked'])

In [32]:
x_test_rem

Pclass  SibSp  Parch     Fare
526       2      0      0  10.5000
468       3      0      0   7.7250
196       3      0      0   7.7500
119       3      4      2  31.2750
889       1      0      0  30.0000
..      ...    ...    ...      ...
586       2      0      0  15.0000
79        3      0      0  12.4750
161       2      0      0  15.7500
281       3      0      0   7.8542
646       3      0      0   7.8958

[179 rows x 4 columns]

In [33]:
x_train_transformed = np.concatenate((x_train_rem,x_train_age,x_train_gender,x_train_embark),axis=1)

In [34]:
x_train_transformed

array([[3., 0., 0., ..., 1., 0., 0.],
       [3., 0., 0., ..., 1., 0., 0.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(712, 10))

In [35]:
x_test_transformed = np.concatenate((x_test_rem,x_test_age,x_test_gender,x_test_embarked),axis = 1)

In [36]:
x_test_transformed

array([[2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 1., 0.],
       [3., 0., 0., ..., 0., 1., 0.],
       ...,
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.]], shape=(179, 10))

In [37]:
type(y_train)

pandas.core.frame.DataFrame

In [38]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [39]:
y_pred = clf.predict(x_test_transformed)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0])

In [40]:
from sklearn.metrics import accuracy_score


In [41]:
accuracy_score(y_true=y_test,y_pred=y_pred)

0.7374301675977654

In [42]:
import pickle

In [47]:
pickle.dump(ohe,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))


In [ ]:
import os
print(os.getcwd())  # Check the current directory

d:\featureEngineering\featureEngineering
